apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yomu-ingress
  namespace: yomu
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: yomu.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yomu-api
            port:
              number: 80
  - host: yomu.takashiaihara.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yomu-api
            port:
              number: 80
