apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yomu
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TakashiAihara/yomu
    targetRevision: main
    path: k8s/yomu
  destination:
    server: https://kubernetes.default.svc
    namespace: yomu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
